behaviors:
  PPO-BASE:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 16384
      learning_rate: 0.0001
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
      shared_critic: true
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 20000000
    time_horizon: 64
    summary_freq: 2000
    threaded: true
  PPO-TH-128:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 16384
      learning_rate: 0.0001
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
      shared_critic: true
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 20000000
    time_horizon: 128
    summary_freq: 2000
    threaded: true
  PPO-TH-256:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 16384
      learning_rate: 0.0001
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
      shared_critic: true
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 20000000
    time_horizon: 256
    summary_freq: 2000
    threaded: true
  PPO-TH-512:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 16384
      learning_rate: 0.0001
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
      shared_critic: true
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 20000000
    time_horizon: 512
    summary_freq: 2000
    threaded: true

  