behaviors:
  PPO:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2816
      buffer_size: 102400
      learning_rate: 0.0001
      epsilon: 0.2
      lambd: 0.925
      num_epoch: 5
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    time_horizon: 1048
    max_steps: 4000000
    summary_freq: 2000
    keep_checkpoints: 5
    checkpoint_interval: 1000000
    threaded: true
  SAC:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.00006
      learning_rate_schedule: constant
      batch_size: 256
      buffer_size: 200000
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 10.0
      save_replay_buffer: false
      init_entcoef: 0.5
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 4000000
    time_horizon: 64
    summary_freq: 2000
    threaded: true
  SAC-Test:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.00006
      learning_rate_schedule: constant
      batch_size: 512
      buffer_size: 299520
      buffer_init_steps: 2000
      tau: 0.005
      steps_per_update: 5.0
      save_replay_buffer: false
      init_entcoef: 0.5
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 4000000
    time_horizon: 64
    summary_freq: 2000
    threaded: true