behaviors:
  SAC-Test-1-TH-LOW:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.00006
      learning_rate_schedule: constant
      batch_size: 256
      buffer_size: 200000
      buffer_init_steps: 2000000 
      tau: 0.005
      steps_per_update: 5
      save_replay_buffer: false
      init_entcoef: 1.0 
    network_settings:
      normalize: true 
      hidden_units: 256 # 128 vorher
      num_layers: 4 #2 vorher
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 12000000
    time_horizon: 32
    summary_freq: 2000
    threaded: true