behaviors:
  SAC-Test-1:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.00006
      learning_rate_schedule: constant
      batch_size: 256
      buffer_size: 200000
      buffer_init_steps: 20000 #0 vorher
      tau: 0.005
      steps_per_update: 5 #10 vorher
      save_replay_buffer: false
      init_entcoef: 1.0 #0.5 vorher
    network_settings:
      normalize: true #false vorher
      hidden_units: 128
      num_layers: 3 #2 vorher
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 8000000
    time_horizon: 64
    summary_freq: 2000
    threaded: true