behaviors:
  SAC-Test-1:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.00006
      learning_rate_schedule: constant
      batch_size: 512 #256 vorher
      buffer_size: 200000
      buffer_init_steps: 2000 #0 vorher
      tau: 0.005
      steps_per_update: 3 #10 vorher
      save_replay_buffer: false
      init_entcoef: 1.0 #0.5 vorher
    network_settings:
      normalize: true #false vorher
      hidden_units: 128
      num_layers: 3 #2 vorher
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 4000000
    time_horizon: 64
    summary_freq: 2000
    threaded: true
  SAC-Test-2:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0001 #0.00006 vorher
      learning_rate_schedule: linear
      batch_size: 512 #256 vorher
      buffer_size: 600000 #299k vorher
      buffer_init_steps: 2000
      tau: 0.005
      steps_per_update: 3
      save_replay_buffer: false
      init_entcoef: 1.0
    network_settings:
      normalize: true #false vorher
      hidden_units: 128
      num_layers: 3 #2 vorher
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 4000000
    time_horizon: 512 #64 vorher
    summary_freq: 2000
    threaded: true