behaviors:
  PPO-1:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 16384
      learning_rate: 0.0001
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
      shared_critic: true
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 10000000
    time_horizon: 64
    summary_freq: 2000
    threaded: true
 
  PPO-2:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 16384
      learning_rate: 0.0001
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
      shared_critic: true
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 10000000
    time_horizon: 2048
    summary_freq: 2000
    threaded: true

  PPO-3:
    trainer_type: ppo
    hyperparameters:
      batch_size: 5120
      buffer_size: 409600
      learning_rate: 0.0001
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
      shared_critic: true
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 10000000
    time_horizon: 64
    summary_freq: 2000
    threaded: true
