behaviors:
  PPO:
    trainer_type: ppo
    hyperparameters:
      batch_size: 5120
      buffer_size: 2560
      learning_rate: 0.0001
      epsilon: 0.2
      lambd: 0.925
      num_epoch: 5
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    time_horizon: 32
    max_steps: 8000000
    summary_freq: 8000
    keep_checkpoints: 5
    checkpoint_interval: 1000000
    threaded: true
